package ClassDiagramDSL.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_RelationType extends EnumerationDescriptorBase {

  public EnumerationDescriptor_RelationType() {
    super(0x1c18981f779a4434L, 0xa3572f05772a8d5eL, 0x5bec2edb52cfeda3L, "RelationType", "r:ff50e1df-308e-4636-8e42-e49a8e24f016(ClassDiagramDSL.structure)/6623720671477231011");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_relation1_0 = new EnumerationDescriptor.MemberDescriptor("relation1", "<|--", 0x5bec2edb52cfeda4L, "r:ff50e1df-308e-4636-8e42-e49a8e24f016(ClassDiagramDSL.structure)/6623720671477231012");
  private final EnumerationDescriptor.MemberDescriptor myMember_relation2_0 = new EnumerationDescriptor.MemberDescriptor("relation2", "*--", 0x5bec2edb52cfedb2L, "r:ff50e1df-308e-4636-8e42-e49a8e24f016(ClassDiagramDSL.structure)/6623720671477231026");
  private final EnumerationDescriptor.MemberDescriptor myMember_relation3_0 = new EnumerationDescriptor.MemberDescriptor("relation3", "o--", 0x5bec2edb52cfedb5L, "r:ff50e1df-308e-4636-8e42-e49a8e24f016(ClassDiagramDSL.structure)/6623720671477231029");
  private final EnumerationDescriptor.MemberDescriptor myMember_relation4_0 = new EnumerationDescriptor.MemberDescriptor("relation4", "..", 0x5bec2edb52cfedb9L, "r:ff50e1df-308e-4636-8e42-e49a8e24f016(ClassDiagramDSL.structure)/6623720671477231033");
  private final EnumerationDescriptor.MemberDescriptor myMember_relation5_0 = new EnumerationDescriptor.MemberDescriptor("relation5", "--", 0x5bec2edb52cfedbeL, "r:ff50e1df-308e-4636-8e42-e49a8e24f016(ClassDiagramDSL.structure)/6623720671477231038");
  private final EnumerationDescriptor.MemberDescriptor myMember_relation6_0 = new EnumerationDescriptor.MemberDescriptor("relation6", "<|..", 0x5bec2edb52cfedc4L, "r:ff50e1df-308e-4636-8e42-e49a8e24f016(ClassDiagramDSL.structure)/6623720671477231044");
  private final EnumerationDescriptor.MemberDescriptor myMember_relation7_0 = new EnumerationDescriptor.MemberDescriptor("relation7", "-->", 0x5bec2edb52cfedcbL, "r:ff50e1df-308e-4636-8e42-e49a8e24f016(ClassDiagramDSL.structure)/6623720671477231051");
  private final EnumerationDescriptor.MemberDescriptor myMember_relation8_0 = new EnumerationDescriptor.MemberDescriptor("relation8", "..>", 0x5bec2edb52cfedd3L, "r:ff50e1df-308e-4636-8e42-e49a8e24f016(ClassDiagramDSL.structure)/6623720671477231059");
  private final EnumerationDescriptor.MemberDescriptor myMember_relation9_0 = new EnumerationDescriptor.MemberDescriptor("relation9", "..|>", 0x5bec2edb52cfeddcL, "r:ff50e1df-308e-4636-8e42-e49a8e24f016(ClassDiagramDSL.structure)/6623720671477231068");
  private final EnumerationDescriptor.MemberDescriptor myMember_relation10_0 = new EnumerationDescriptor.MemberDescriptor("relation10", "<--*", 0x5bec2edb52cfede6L, "r:ff50e1df-308e-4636-8e42-e49a8e24f016(ClassDiagramDSL.structure)/6623720671477231078");
  private final EnumerationDescriptor.MemberDescriptor myMember_relation11_0 = new EnumerationDescriptor.MemberDescriptor("relation11", "#--", 0x5bec2edb52cfedf1L, "r:ff50e1df-308e-4636-8e42-e49a8e24f016(ClassDiagramDSL.structure)/6623720671477231089");
  private final EnumerationDescriptor.MemberDescriptor myMember_relation12_0 = new EnumerationDescriptor.MemberDescriptor("relation12", "x--", 0x5bec2edb52cfedfdL, "r:ff50e1df-308e-4636-8e42-e49a8e24f016(ClassDiagramDSL.structure)/6623720671477231101");
  private final EnumerationDescriptor.MemberDescriptor myMember_relation13_0 = new EnumerationDescriptor.MemberDescriptor("relation13", "}--", 0x5bec2edb52cfee0aL, "r:ff50e1df-308e-4636-8e42-e49a8e24f016(ClassDiagramDSL.structure)/6623720671477231114");
  private final EnumerationDescriptor.MemberDescriptor myMember_relation14_0 = new EnumerationDescriptor.MemberDescriptor("relation14", "+--", 0x5bec2edb52cfee18L, "r:ff50e1df-308e-4636-8e42-e49a8e24f016(ClassDiagramDSL.structure)/6623720671477231128");
  private final EnumerationDescriptor.MemberDescriptor myMember_relation15_0 = new EnumerationDescriptor.MemberDescriptor("relation15", "^--", 0x5bec2edb52cfee27L, "r:ff50e1df-308e-4636-8e42-e49a8e24f016(ClassDiagramDSL.structure)/6623720671477231143");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x1c18981f779a4434L, 0xa3572f05772a8d5eL, 0x5bec2edb52cfeda3L, 0x5bec2edb52cfeda4L, 0x5bec2edb52cfedb2L, 0x5bec2edb52cfedb5L, 0x5bec2edb52cfedb9L, 0x5bec2edb52cfedbeL, 0x5bec2edb52cfedc4L, 0x5bec2edb52cfedcbL, 0x5bec2edb52cfedd3L, 0x5bec2edb52cfeddcL, 0x5bec2edb52cfede6L, 0x5bec2edb52cfedf1L, 0x5bec2edb52cfedfdL, 0x5bec2edb52cfee0aL, 0x5bec2edb52cfee18L, 0x5bec2edb52cfee27L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_relation1_0, myMember_relation2_0, myMember_relation3_0, myMember_relation4_0, myMember_relation5_0, myMember_relation6_0, myMember_relation7_0, myMember_relation8_0, myMember_relation9_0, myMember_relation10_0, myMember_relation11_0, myMember_relation12_0, myMember_relation13_0, myMember_relation14_0, myMember_relation15_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "relation1":
        return myMember_relation1_0;
      case "relation2":
        return myMember_relation2_0;
      case "relation3":
        return myMember_relation3_0;
      case "relation4":
        return myMember_relation4_0;
      case "relation5":
        return myMember_relation5_0;
      case "relation6":
        return myMember_relation6_0;
      case "relation7":
        return myMember_relation7_0;
      case "relation8":
        return myMember_relation8_0;
      case "relation9":
        return myMember_relation9_0;
      case "relation10":
        return myMember_relation10_0;
      case "relation11":
        return myMember_relation11_0;
      case "relation12":
        return myMember_relation12_0;
      case "relation13":
        return myMember_relation13_0;
      case "relation14":
        return myMember_relation14_0;
      case "relation15":
        return myMember_relation15_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
