package ClassDiagramDSL.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_Visibility extends EnumerationDescriptorBase {

  public EnumerationDescriptor_Visibility() {
    super(0x1c18981f779a4434L, 0xa3572f05772a8d5eL, 0x5bec2edb52ccec41L, "Visibility", "r:ff50e1df-308e-4636-8e42-e49a8e24f016(ClassDiagramDSL.structure)/6623720671477034049");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_public_0 = new EnumerationDescriptor.MemberDescriptor("public", "+", 0x5bec2edb52ccec42L, "r:ff50e1df-308e-4636-8e42-e49a8e24f016(ClassDiagramDSL.structure)/6623720671477034050");
  private final EnumerationDescriptor.MemberDescriptor myMember_private_0 = new EnumerationDescriptor.MemberDescriptor("private", "-", 0x5bec2edb52ccec43L, "r:ff50e1df-308e-4636-8e42-e49a8e24f016(ClassDiagramDSL.structure)/6623720671477034051");
  private final EnumerationDescriptor.MemberDescriptor myMember_protected_0 = new EnumerationDescriptor.MemberDescriptor("protected", "#", 0x5bec2edb52ccec46L, "r:ff50e1df-308e-4636-8e42-e49a8e24f016(ClassDiagramDSL.structure)/6623720671477034054");
  private final EnumerationDescriptor.MemberDescriptor myMember_package_0 = new EnumerationDescriptor.MemberDescriptor("package", "~", 0x5bec2edb52ccec4aL, "r:ff50e1df-308e-4636-8e42-e49a8e24f016(ClassDiagramDSL.structure)/6623720671477034058");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x1c18981f779a4434L, 0xa3572f05772a8d5eL, 0x5bec2edb52ccec41L, 0x5bec2edb52ccec42L, 0x5bec2edb52ccec43L, 0x5bec2edb52ccec46L, 0x5bec2edb52ccec4aL);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_public_0, myMember_private_0, myMember_protected_0, myMember_package_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "public":
        return myMember_public_0;
      case "private":
        return myMember_private_0;
      case "protected":
        return myMember_protected_0;
      case "package":
        return myMember_package_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
