package ClassDiagramDSL.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import jetbrains.mps.smodel.runtime.DataTypeDescriptor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptAttribute = createDescriptorForAttribute();
  /*package*/ final ConceptDescriptor myConceptClassDiagram = createDescriptorForClassDiagram();
  /*package*/ final ConceptDescriptor myConceptClassDiagramElement = createDescriptorForClassDiagramElement();
  /*package*/ final ConceptDescriptor myConceptClassDiagramRepository = createDescriptorForClassDiagramRepository();
  /*package*/ final ConceptDescriptor myConceptClassElement = createDescriptorForClassElement();
  /*package*/ final ConceptDescriptor myConceptClassElementMember = createDescriptorForClassElementMember();
  /*package*/ final ConceptDescriptor myConceptInterfaceElement = createDescriptorForInterfaceElement();
  /*package*/ final ConceptDescriptor myConceptMethod = createDescriptorForMethod();
  /*package*/ final ConceptDescriptor myConceptMethodArgument = createDescriptorForMethodArgument();
  /*package*/ final ConceptDescriptor myConceptRelationElement = createDescriptorForRelationElement();
  /*package*/ final EnumerationDescriptor myEnumerationRelationType = new EnumerationDescriptor_RelationType();
  /*package*/ final EnumerationDescriptor myEnumerationVisibility = new EnumerationDescriptor_Visibility();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptAttribute, myConceptClassDiagram, myConceptClassDiagramElement, myConceptClassDiagramRepository, myConceptClassElement, myConceptClassElementMember, myConceptInterfaceElement, myConceptMethod, myConceptMethodArgument, myConceptRelationElement);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.Attribute:
        return myConceptAttribute;
      case LanguageConceptSwitch.ClassDiagram:
        return myConceptClassDiagram;
      case LanguageConceptSwitch.ClassDiagramElement:
        return myConceptClassDiagramElement;
      case LanguageConceptSwitch.ClassDiagramRepository:
        return myConceptClassDiagramRepository;
      case LanguageConceptSwitch.ClassElement:
        return myConceptClassElement;
      case LanguageConceptSwitch.ClassElementMember:
        return myConceptClassElementMember;
      case LanguageConceptSwitch.InterfaceElement:
        return myConceptInterfaceElement;
      case LanguageConceptSwitch.Method:
        return myConceptMethod;
      case LanguageConceptSwitch.MethodArgument:
        return myConceptMethodArgument;
      case LanguageConceptSwitch.RelationElement:
        return myConceptRelationElement;
      default:
        return null;
    }
  }

  @Override
  public Collection<DataTypeDescriptor> getDataTypeDescriptors() {
    return Arrays.asList(myEnumerationRelationType, myEnumerationVisibility);
  }

  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForAttribute() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("ClassDiagramDSL", "Attribute", 0x1c18981f779a4434L, 0xa3572f05772a8d5eL, 0x5bec2edb52c5a5adL);
    b.class_(false, false, false);
    b.super_("ClassDiagramDSL.structure.ClassElementMember", 0x1c18981f779a4434L, 0xa3572f05772a8d5eL, 0x5bec2edb52c5a558L);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:ff50e1df-308e-4636-8e42-e49a8e24f016(ClassDiagramDSL.structure)/6623720671476557229");
    b.version(2);
    b.property("visibility", 0x5bec2edb52c5a5b0L).type(MetaIdFactory.dataTypeId(0x1c18981f779a4434L, 0xa3572f05772a8d5eL, 0x5bec2edb52ccec41L)).origin("6623720671476557232").done();
    b.property("type", 0x5bec2edb52cee930L).type(PrimitiveTypeId.STRING).origin("6623720671477164336").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForClassDiagram() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("ClassDiagramDSL", "ClassDiagram", 0x1c18981f779a4434L, 0xa3572f05772a8d5eL, 0x2821a260f6f18a77L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:ff50e1df-308e-4636-8e42-e49a8e24f016(ClassDiagramDSL.structure)/2891770973092153975");
    b.version(2);
    b.aggregate("classDiagramElements", 0x2821a260f6f23d2dL).target(0x1c18981f779a4434L, 0xa3572f05772a8d5eL, 0x2821a260f6f23d2aL).optional(true).ordered(true).multiple(true).origin("2891770973092199725").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForClassDiagramElement() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("ClassDiagramDSL", "ClassDiagramElement", 0x1c18981f779a4434L, 0xa3572f05772a8d5eL, 0x2821a260f6f23d2aL);
    b.class_(false, true, false);
    b.origin("r:ff50e1df-308e-4636-8e42-e49a8e24f016(ClassDiagramDSL.structure)/2891770973092199722");
    b.version(2);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForClassDiagramRepository() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("ClassDiagramDSL", "ClassDiagramRepository", 0x1c18981f779a4434L, 0xa3572f05772a8d5eL, 0x2821a260f6f18a76L);
    b.class_(false, false, true);
    b.origin("r:ff50e1df-308e-4636-8e42-e49a8e24f016(ClassDiagramDSL.structure)/2891770973092153974");
    b.version(2);
    b.aggregate("classDiagrams", 0x2821a260f6f18a7aL).target(0x1c18981f779a4434L, 0xa3572f05772a8d5eL, 0x2821a260f6f18a77L).optional(true).ordered(true).multiple(true).origin("2891770973092153978").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForClassElement() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("ClassDiagramDSL", "ClassElement", 0x1c18981f779a4434L, 0xa3572f05772a8d5eL, 0x5bec2edb52c440dcL);
    b.class_(false, false, false);
    b.super_("ClassDiagramDSL.structure.ClassDiagramElement", 0x1c18981f779a4434L, 0xa3572f05772a8d5eL, 0x2821a260f6f23d2aL);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:ff50e1df-308e-4636-8e42-e49a8e24f016(ClassDiagramDSL.structure)/6623720671476465884");
    b.version(2);
    b.aggregate("classElementMembers", 0x5bec2edb52c5a55bL).target(0x1c18981f779a4434L, 0xa3572f05772a8d5eL, 0x5bec2edb52c5a558L).optional(true).ordered(true).multiple(true).origin("6623720671476557147").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForClassElementMember() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("ClassDiagramDSL", "ClassElementMember", 0x1c18981f779a4434L, 0xa3572f05772a8d5eL, 0x5bec2edb52c5a558L);
    b.class_(false, true, false);
    b.origin("r:ff50e1df-308e-4636-8e42-e49a8e24f016(ClassDiagramDSL.structure)/6623720671476557144");
    b.version(2);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForInterfaceElement() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("ClassDiagramDSL", "InterfaceElement", 0x1c18981f779a4434L, 0xa3572f05772a8d5eL, 0x5bec2edb52c61d2dL);
    b.class_(false, false, false);
    b.super_("ClassDiagramDSL.structure.ClassDiagramElement", 0x1c18981f779a4434L, 0xa3572f05772a8d5eL, 0x2821a260f6f23d2aL);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:ff50e1df-308e-4636-8e42-e49a8e24f016(ClassDiagramDSL.structure)/6623720671476587821");
    b.version(2);
    b.aggregate("methods", 0x5bec2edb52cc7770L).target(0x1c18981f779a4434L, 0xa3572f05772a8d5eL, 0x5bec2edb52c61d43L).optional(true).ordered(true).multiple(true).origin("6623720671477004144").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForMethod() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("ClassDiagramDSL", "Method", 0x1c18981f779a4434L, 0xa3572f05772a8d5eL, 0x5bec2edb52c61d43L);
    b.class_(false, false, false);
    b.super_("ClassDiagramDSL.structure.ClassElementMember", 0x1c18981f779a4434L, 0xa3572f05772a8d5eL, 0x5bec2edb52c5a558L);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:ff50e1df-308e-4636-8e42-e49a8e24f016(ClassDiagramDSL.structure)/6623720671476587843");
    b.version(2);
    b.property("visibility", 0x5bec2edb52c61d46L).type(MetaIdFactory.dataTypeId(0x1c18981f779a4434L, 0xa3572f05772a8d5eL, 0x5bec2edb52ccec41L)).origin("6623720671476587846").done();
    b.property("returnType", 0x5bec2edb52c61d48L).type(PrimitiveTypeId.STRING).origin("6623720671476587848").done();
    b.aggregate("methodArguments", 0x5bec2edb52c673b7L).target(0x1c18981f779a4434L, 0xa3572f05772a8d5eL, 0x5bec2edb52c6738eL).optional(true).ordered(true).multiple(true).origin("6623720671476609975").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForMethodArgument() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("ClassDiagramDSL", "MethodArgument", 0x1c18981f779a4434L, 0xa3572f05772a8d5eL, 0x5bec2edb52c6738eL);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:ff50e1df-308e-4636-8e42-e49a8e24f016(ClassDiagramDSL.structure)/6623720671476609934");
    b.version(2);
    b.property("type", 0x5bec2edb52c67391L).type(PrimitiveTypeId.STRING).origin("6623720671476609937").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForRelationElement() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("ClassDiagramDSL", "RelationElement", 0x1c18981f779a4434L, 0xa3572f05772a8d5eL, 0x5bec2edb52cfeda0L);
    b.class_(false, false, false);
    b.super_("ClassDiagramDSL.structure.ClassDiagramElement", 0x1c18981f779a4434L, 0xa3572f05772a8d5eL, 0x2821a260f6f23d2aL);
    b.origin("r:ff50e1df-308e-4636-8e42-e49a8e24f016(ClassDiagramDSL.structure)/6623720671477231008");
    b.version(2);
    b.property("relationType", 0x5bec2edb52cfee37L).type(MetaIdFactory.dataTypeId(0x1c18981f779a4434L, 0xa3572f05772a8d5eL, 0x5bec2edb52cfeda3L)).origin("6623720671477231159").done();
    b.property("cardinality1", 0x5bec2edb52cfee3fL).type(PrimitiveTypeId.STRING).origin("6623720671477231167").done();
    b.property("cardinality2", 0x5bec2edb52cfee42L).type(PrimitiveTypeId.STRING).origin("6623720671477231170").done();
    b.property("label", 0x5bec2edb52cfee46L).type(PrimitiveTypeId.STRING).origin("6623720671477231174").done();
    b.associate("class1", 0x5bec2edb52d7bc2aL).target(0x1c18981f779a4434L, 0xa3572f05772a8d5eL, 0x5bec2edb52c440dcL).optional(false).origin("6623720671477742634").done();
    b.associate("class2", 0x5bec2edb52d7bc30L).target(0x1c18981f779a4434L, 0xa3572f05772a8d5eL, 0x5bec2edb52c440dcL).optional(false).origin("6623720671477742640").done();
    return b.create();
  }
}
